
######## ember-osf settings ########
# local:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

stage:
    CLIENT_ID: 7ad79c53a5c34d929c3425818af08cf4
    PERSONAL_ACCESS_TOKEN: pNcOXNBBI16D3oBnQeWED9yyyRCfPbDosmg1b76t
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:4200/login/

# stage2:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

test:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:4200/login/
######### end ember-osf ##########
