
######## ember-osf settings ########
# local:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

stage:
    CLIENT_ID: ab6efcaa06434f1583e26006ab5dda60
    PERSONAL_ACCESS_TOKEN: UBYe40hJPTQb1wdX21QxQnH6CjOsF4f62jz8FFp2
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:4200/

# stage2:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

test:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:4200/login/
######### end ember-osf ##########
